### ISSUE TITLE
cURL error: [60] SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by Adzter** [toolani/paypal-ipn-verifier-php#1]
When using the IPN simulator I'm getting the following error:
cURL error: [60] SSL certificate problem: unable to get local issuer certificate

Sandbox mode is enabled and the certificate is the one provided in this github project.

**Comment by petert82** [comment]
Sorry for the delay getting back to you, but I'm not seeing that behaviour in our testing with the sandbox.

What OS and version of PHP are you using?

**Comment by Adzter** [comment]
Issue seems to have fixed itself, didn't do anything but next time an IPN call came it, it went through fine. Might've been a temporary issue with my host.
